# MongoDB
spring.data.mongodb.uri=mongodb+srv://Katarinabluu_DB:g0oWZLVfs48jX1wC@cluster0.gxk8exg.mongodb.net/vtmen
spring.data.mongodb.auto-index-creation=true

# Server
server.port=8081

# Allow bean overriding
spring.main.allow-bean-definition-overriding=true
