# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/vtmen
spring.data.mongodb.auto-index-creation=true

# Server
server.port=8081

# Allow bean overriding
spring.main.allow-bean-definition-overriding=true
