# MongoDB
spring.data.mongodb.uri=mongodb+srv://Katarinabluu_DB:g0oWZLVfs48jX1wC@cluster0.gxk8exg.mongodb.net/vtmen
spring.data.mongodb.auto-index-creation=true

# Server
server.port=${PORT:8080}

# Allow bean overriding
spring.main.allow-bean-definition-overriding=true

# Redis
spring.data.redis.url=redis://default:AhbPddlsXSrNXLSiAcznAGjonOqFwMXc@yamabiko.proxy.rlwy.net:32274

# Notify the other project's backend (localhost:8081) when an order is created
notify.backend.url=http://localhost:8081/api/orders/notify